# Generated by Django 6.1.1 on 2026-10-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uk', models.TextField(verbose_name='Текст (UA)')),
                ('text_en', models.TextField(blank=True, verbose_name='Text (EN)')),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, verbose_name='Назва (UA)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (EN)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_uk', models.CharField(max_length=255, verbose_name='Адреса (UA)')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Address (EN)')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='Google Maps')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок (UA)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (EN)')),
                ('content_uk', models.TextField(verbose_name='Текст (UA)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=150, verbose_name='Назва (UA)')),
                ('title_en', models.CharField(blank=True, max_length=150, verbose_name='Title (EN)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (UA)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна, грн')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Позиція меню',
                'verbose_name_plural': 'Позиції меню',
            },
        ),
    ]
