# Generated by Django 6.1.1 on 2026-10-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ціна, грн (якщо немає версій)'),
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(blank=True, help_text='Наприклад: Мала 300 мл', max_length=50, verbose_name='Версія (UA)')),
                ('name_en', models.CharField(blank=True, help_text='For example: Small 300 ml', max_length=50, verbose_name='Version (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна, грн')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='restaurant.menuitem', verbose_name='Позиція')),
            ],
            options={
                'verbose_name': 'Версія',
                'verbose_name_plural': 'Версії',
                'ordering': ['price'],
            },
        ),
    ]
